# Generated by Django 3.1 on 2021-03-25 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="images/")),
                (
                    "photo_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("panorama", "Panorama"),
                            ("recipe", "Recipe"),
                            ("wildlife", "Wildlife"),
                        ],
                        help_text="The 'type' of photo being uploaded",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
